<a href="https://colab.research.google.com/github/Clalloures/TensorFlow/blob/main/Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow

## Deep Learnin Frameworks


- TensorFlow
- Keras
- PyTorch
- Caffe
- Theano
- DL4J
- Chainer

## What is TensorFlow?

TensorFlow is a popular open-source library released in 2015 by Google Brain team for building Machine Learning and Deep Learning Models. It is based on Python programming language and performs numerical computations using data flow graphs to buil models.

- It works efficientlt with multi-dimensional arrays.
- Provides scalability of computation across machines and large data sets.
- Support fast debugging and model building
- Has a large community and provides TensorBoard to visualize the model

## TensorFlow Applications

- Face Detection
- Language Translation
- Fraud Detection
- Video Detection


## Tensors?

TensorFlow is derived from its core componet known as Tensor
A tensor is a vector or a matrix of n-dimensions that represent all types of data. 

In TensorFlow, tensors are defined by a unit of dimensionality called as rank.

Tensorflow performs computations with the help of dataflow graphs,It has nodes that represent the operatiosn in your model.

## TensorFlow 1.0 vs 2.0

TesorFlow 2.0 support Eager execution by default. It allows you buld your model and run them instantly.

Keras is the high level API in TensorFlow 2.0. Keras is the official high-level API of TensorFlow 2.0. It has incorporated Keras as tf.keras. Keras provides a number of model building APIs such as Sequential, Functional, and Subclassing, so you can choose the right level of abstraction for your project.

In TensorFlow 1.x, in order to use tf.layes as variables, we had to write tf.variable block. In TensorFlow 2.0, all the layers created using tf.layers can be put into a tf.Keras.Sequential definition.








In [1]:
import tensorflow as tf
print(("Your TensorFlow version: {0}").format(tf.__version__))


Your TensorFlow version: 2.3.0


In [3]:
# Tensor
A = tf.constant([[4, 3],
                [6, 1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [7]:
# Variable
V = tf.Variable([[3,1],
                 [5,2]])

B = tf.constant([[7,8],
                [4,5]])

print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]], dtype=int32)>

In [8]:
# Concatenate columns
AB_concatenated = tf.concat(values = [A,B], axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>